### ISSUE TITLE
Make the content of this repo served as https

### ISSUE THREAD

**Issue by dontcallmedom** [w3ctag/tagdocs#1]
Because this repo was created a long time ago, at that time Github pages were not systematically served as https. This has to be manually enabled in the repo settings at https://github.com/w3ctag/tagdocs/settings#pages-https-redirect-feature which I think it would make sense to turn on (even if the content served is probably not all that up to date in the first place at the moment)

**Comment by dbaron** [comment]
Done.  Thanks for pointing this out.
